### ISSUE TITLE
Change default authentication to DB ?

### ISSUE THREAD

**Issue by JohnSmith-LT** [WebPA/WebPA#13]
Out of the box authentication is set to SAML. Without changing any settings I was able to 'login' as both Admin and as a default student account I added but upon further testing I realised that the password was not being checked...

Not sure if this is a problem with the SAML authenticator (surely it would be best to not authenticate if it's unable to contact the authentication service since I didn't add one??)

But anyway, the problem is that this could be a gotcha for new installs who think authentication is taking place when in fact, if you know the username then you can get in by adding a non-empty password...

This has been checked on XAMPP on Mac only so not sure if the same happens on a proper server install.

**Comment by Sephster** [comment]
I don't think the SAML implementation was ever completed. From my investigations, the SAML implementation in master appears to be only half implemented.

I've updated the code to change the default authenticator to DB. I will remove the existing SAML code in a different branch which adds autoloading to WebPA. Thanks @JohnSmith-LT
