### ISSUE TITLE
mySQL compatibility for server running php7

### ISSUE THREAD

**Issue by huddsweb** [WebPA/WebPA#18]
HI there - just tried installing this for one of our staff members on one of our ubuntu 16 servers running php7. Looks like it's using the deprecated/removed mysql_* functions for the database, and so it won't work with PHP7. Are there any plans to update webpa to use mysqli or PDO? I'm keen to get it running as it looks really useful.

Thanks in advance and thanks for your work on this software.

**Comment by mcrauwel** [comment]
I have a pull request open (#5) that implemented the conversion to mysqli (among a bunch of other things). Feel free to test that version and report bugs/status here...

**Comment by huddsweb** [comment]
Ah, didn't spot that, many thanks, will do.

**Comment by Sephster** [comment]
@huddsweb the latest 3.0.0 branch is fully compatible with PHP 7.0+. I will mark this issue as resolved but if you do have any comments or questions please feel free to get back in touch. Many thanks.
