### ISSUE TITLE
Mis-tagged release causing installation error

### ISSUE THREAD

**Issue by spvickers** [WebPA/WebPA#73]
Version 3.0.4 appears to have been given a tag of v3.04 which is causing Packagist to install this version rather than the latest (3.0.7).  Since this version also includes a syntax error causing it not to run, this is particularly unhelpful.

**Comment by Sephster** [comment]
Thanks Stephen. I knew about the mistag but didn't realise it was forcing composer to install that version but it makes sense. Out of interest, what is the syntax error? I will look at how to resolve this today. Thanks for reporting.

**Comment by spvickers** [comment]
The syntax error was a missing closing bracket on line 553 of includes\classes\class_engcis.php.  It does not look like it is an issue in other releases.  Cheers.

**Comment by Sephster** [comment]
Thanks for this. That should be the tag fixed now. You might need to run `git pull --prune --tags` locally or just delete the repo and install again.

I should be tagging a new release some time next week which adds auto-loading to the system and allow it to work with PHP 7.4. Am working on adding dependency injection at the moment. Cheers

**Comment by spvickers** [comment]
Thanks.  I shall try to check that it does not break my LTI module (which I suspect is the only implementation of an add-on module for WebPA).  Let me know if you have any recommendations for how best to load classes in add-on modules.  At present I just use a Composer autoload.php file.
