### ISSUE TITLE
Purpose of includes/classes/LTIAuthenticator.php file

### ISSUE THREAD

**Issue by spvickers** [WebPA/WebPA#76]
This file seems to have started out life as class_lti_authenticator.php and contained a class named DBAuthenticator.  When the autoloading was added the file was renamed to LTIAuthenticator.php and the class was renamed to LTIAuthenticator.  The code in this class appears to be equivalent to the DBAuthenticator class file and seems to have nothing to do with LTI.

Does anyone know why this file exists?

It looks like it should be deleted/deprecated to avoid any confusion with how LTI connections really work.  Alternatively it could be changed to being an extension of the DBAuthenticator class so that the equivalence is clearer which would also allow any implementation with "LTI" included in their $LOGIN_AUTHENTICATORS array to continue to work.

**Comment by Sephster** [comment]
As far as I can tell, the version of WebPA initially uploaded to GitHub wasn't identical to the latest version that was available for download. It seems some things in the repo were in a partially developed state.

Unfortunately I'm not aware of the history of the file. I agree though, that the file seems to be useless so will be safe to delete. There is already a DBAuthenticator so I think I might have just renamed this to LTIAuthenticator to avoid name clashes but this is clearly a mistake. Thanks for spotting this Stephen. I will issue a fix shortly.

**Comment by Sephster** [comment]
Closing as merged in PR #77
