### ISSUE TITLE
Error when trying to add criterion to assessment form

### ISSUE THREAD

**Issue by richeduni** [WebPA/WebPA#81]
If I go to any assessment form and click the 'add new criterion' button, I get the following error:

`Warning: include_once(/tutors/forms/edit/add_question/likert/class_wizardstep_1.php): failed to open stream: No such file or directory in /var/www/html/WebPA/src/includes/classes/Wizard.php on line`

Please see attached screenshot of error.
<img width="1440" alt="Screenshot 2021-02-16 at 09 56 59" src="https://user-images.githubusercontent.com/22029618/108047134-5cf7ed00-703d-11eb-85da-ff4eda08e94d.png">

**Comment by Sephster** [comment]
I've had a look into this and this occurs when the `DOC__ROOT` is not set in the main config folder. Have spoken with @richeduni and confirmed this was the issue. No requirements to fix.
