### ISSUE TITLE
Possible issue with APP__DB_PORT constant

### ISSUE THREAD

**Issue by spvickers** [WebPA/WebPA#90]
A new constant has been added in verion 3.2.0 which is used in `includes/inc_global.php` when creating a `DAO` object (line 174).  This parameter is optional in the DAO object constructor and defaults to 3306.  I notice, however, that in the other places where a DAO object is created, the port constant is **not** included and so the default will be used.  The places I have  found are in the following files:

- includes\classes\Authenticator.php
- includes\classes\DBAuthenticator.php
- includes\classes\EngCIS.php
- includes\classes\GroupHandler.php

I have not tested this, but I strongly suspect that this will cause an error with any WebPA instance which is not using the default port when the code in these files is called, but perhaps I am missing something.

**Comment by Sephster** [comment]
Hi Stephen. Thanks for reporting this. We are already using this change in Edinburgh but I might have modified these files so will double check this. If I've missed off these changes from the PR (which looks to be the case) I will issue a new patch asap. Thanks for reporting.

**Comment by Sephster** [comment]
Hi Stephen. Thanks for reporting this. It had indeed been missed off so have released an update now.
